#pragma config(Motor,  motorA,          monMoteur,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
On tourne le moteur dans le sens inverse des aiguilles d’une montre et on l'arrête sur le capteur de contact.
*/
task main()
{

int sens = 1;
while (1){
   while (getTouchValue(S1)==0){}
   sens = - sens;
   setMotorSpeed(motorA,sens*20);
   while (getTouchValue(S1)==1){}
}
}




