#pragma config(Motor,  motorA,          monMoteur,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*On écrit un programme RobotC pour faire tourner un moteur dans le sens des aiguilles d’une montre 
pendant 4 secondes et l'arrêter.
*/
task main()
{


setMotorSpeed(monMoteur,20); // on lance le moteur à une puissance de 20
delay(4000); //le moteur va garder son etat precedent (celui de tourner ) pendant 4s
setMotorSpeed(monMoteur,0); //on arrete le moteur 
delay(500);

}




