#pragma config(Sensor, S3,     ,               sensorEV3_Gyro)
#pragma config(Motor,  motorA,          motoraa,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//






//suivi de consigne


int tab[101];
long fileHandle;
void gyroRateCharacterisation(){



	resetMotorEncoder(motoraa);
	resetGyro(S3);
		for(int puissance = 0; puissance<=100; puissance++){


			setMotorSpeed(motoraa, puissance);
			delay(300);
			tab[puissance]= getGyroRate(S3);
			//setMotorTarget(motoraa, 0,40);
			setMotorTarget(motoraa,0,40);
			delay(500+300);


		}

		  string filename = "gyrodata2.csv";
			fileHandle =fileOpenWrite(filename);
			string viS;
			string puS;
			for(int i=0; i<=100;i++){
				stringFormat(puS, "%d\t%d\n",i,tab[i]);
			fileWriteData (fileHandle,puS, strlen(puS));

				}


		fileClose(fileHandle);
}



task main()
{

gyroRateCharacterisation();
while(1){}

}
